### ISSUE TITLE
terminal looks weird

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1639] opened 2020-04-20 11:22 UTC
The terminal fired up through oni2 looks weird (both font shape, some characters etc):

![Screenshot from 2020-04-20 13-20-49](https://user-images.githubusercontent.com/8382834/79746216-e6e60500-8309-11ea-80a1-85fc1fda78ed.png)

Any idea why? I am using natively bash, with a few customizations on my bashrc, but surprised it looks so weird on onivim2. Very nice that the .bashrc seems to be loaded, though ) .

**Comment by CrossR** [comment] 2020-04-20 11:34
This looks to be a duplicate of https://github.com/onivim/oni2/issues/1456.

Some characters aren't being loaded correctly yet, which probably includes the tick mark you have in your prompt.

**Closed by CrossR** 2020-04-20 11:34 UTC
