### ISSUE TITLE
Can't support Chinese.

### ISSUE THREAD

**Issue by matianhe** [onivim/oni2#1091] opened 2019-12-20 06:44 UTC
![image](https://user-images.githubusercontent.com/24929062/71235432-20e0d380-2337-11ea-8544-9607c4187ea7.png)

**Comment by AlawnCN** [comment] 2020-02-20 06:43
me too

**Comment by AlawnCN** [comment] 2020-04-14 01:36
How soon will it be fixed?

**Comment by glennsl** [comment] 2020-04-14 08:20
This seems like a duplicate of #1293, the issue being a lack of fallback mechanism for missing characters. And if so, a workaround is to use a font that has all the needed characters. The monospace font that's configured on your system by default probably does. Could you try that @AlawnCN  and @matianhe?

**Comment by AlawnCN** [comment] 2020-04-15 01:51
> This seems like a duplicate of #1293, the issue being a lack of fallback mechanism for missing characters. And if so, a workaround is to use a font that has all the needed characters. The monospace font that's configured on your system by default probably does. Could you try that @AlawnCN and @matianhe?

How to configure it on my system by default, my system is macOS and think it should be configured on Oni2 Application?

**Comment by glennsl** [comment] 2020-04-15 06:37
Press `Cmd+Shift+P` to open the Command Palette, then search for "Open Configuration file". Once open, replace or add "editor.fontFamily" using your font of choice as the value.

**Closed** 2020-04-28 06:54 UTC
Labels: A-font, A-i18n, I-daily-editor-blocker, bug
