### ISSUE TITLE
Moving around with the ```gg``` command

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1892] opened 2020-06-07 10:22 UTC
I am on Ubuntu 18.04, Onivim 2 0.4.0 downloaded a few days ago.

In vim I can move with the ```gg``` command in the following ways, not all of them are supported by Onivim2 looks like:

- ```G```: go to the end: ok on both vim and onivim2
- ```gg```: go to the start: ok on vim, not on onivim2. On onivim2, I need to press ```ggg``` to get to the start
- ```ngg``` where n is a number, to jump to line number n. Works on vim, not on onivim2. On onivim2, I can do ```:n``` to go to line number n, but I like it less good, as it is easier to type ```gg``` than ```:```. I can also press ```nggg```, n the line number, but this does not work well either: this goes to the line number the last digit of n, rather than the full number n.

So can you implement the full ```gg``` functionality?

**Comment by glennsl** [comment] 2020-06-07 11:07
These all work as expected for me, on Manjaro. Do you have any custom keybindings that might interfere?

**Comment by jerabaul29** [comment] 2020-06-07 11:26
Mmh, strange. Not that I know about, but I may miss something. Which files do you want me to check for custom keybindings etc?

**Comment by jerabaul29** [comment] 2020-06-07 18:45
This is the content of the keybindings:

```
[
  // See the onivim documentation for details on the format:
  // https://onivim.github.io/docs/configuration/key-bindings
  // Add key bindings here, for example:
  // { "key": "<TAB>", "command": "workbench.action.quickOpen", when: "editorTextFocus" },
  // { "key": "jk", "command": "vim.esc", when: "insertMode" },
  { "key": "gt", "command": "workbench.action.nextEditor", "when": "normalMode" },
  { "key": "gT", "command": "workbench.action.previousEditor", "when": "normalMode" }
]
```

Is there a possibility this explains for the problem? I guess it should not?

**Comment by glennsl** [comment] 2020-06-07 21:38
Yeah, there's a problem with keybinding sequences where they interfere with vim key sequences with the same first character.

Also, it's a pretty exact duplicate of #1691, so I'll close this.

**Closed by glennsl** 2020-06-07 21:38 UTC
Labels: A-configuration, A-input, A-vim, bug
