### ISSUE TITLE
Sidebar exhibits strange behavior when scrolled while no scrollbar is present

### ISSUE THREAD

**Issue by null-dev** [onivim/oni2#616] opened 2019-08-07 15:38 UTC
When scrolling the sidebar using the mouse wheel when there is no scrollbar present (the contents of the sidebar can fit entirely on screen), the sidebar rapidly switches between top and bottom alignment.

Scrolling works fine when a scrollbar is a present (sidebar cannot fit on screen).

See this video for visuals: https://s3.wasabisys.com/nd-public/tmp/onivim2-sidebar-scroll-bug.mp4

OS: Windows 10 x64

**Comment by CrossR** [comment] 2019-08-07 15:56
As far as I know, this is due to https://github.com/revery-ui/revery/issues/467

**Comment by glennsl** [comment] 2019-11-17 17:52
This seems to have been fixed by #621. I can't reproduce it at least.

**Closed by glennsl** 2019-11-17 17:52 UTC
Labels: bug
