### ISSUE TITLE
Different Menu Commands Overlap

### ISSUE THREAD

**Issue by Akin909** [onivim/oni2#210] opened 2019-04-02 23:11 UTC
When switching between `quickopen` and `commandPalette` the commands for both can occasionally render together. This appears to be a regression as we are no longer populating the content of each menu based on type I think.
![image](https://user-images.githubusercontent.com/22454918/55442066-01d1c400-55a5-11e9-94e9-16cc3f058b2d.png)

**Comment by bryphe** [comment] 2019-04-03 00:01
Ah nice catch @Akin909 , sorry for the regression! I think #211 fixes the root cause - but you're right, we do need some identifier - especially for cases coming from the extension host (integration with the VSCode Menu API).

I think it might make sense for us to pivot to a string-based identifier - we could support quickopen / command palette with hardcoded identifiers (ie, `oni.quickopen` and `oni.commandpalette`, and then a convention for identifiers coming from the extensions, like `oni.ext#<some id>`

**Comment by bryphe** [comment] 2019-07-10 03:41
Looks like this is fixed now -

**Closed by bryphe** 2019-07-10 03:41 UTC
Labels: bug
