### ISSUE TITLE
reason-vscode doesn't seem to work in windows

### ISSUE THREAD

**Issue by bikallem** [onivim/oni2#1271] opened 2020-01-28 11:24 UTC
Not sure if the issue is with onivim or reason-vscode, however, reason-vscode is not working for me on Windows.

Windows 10(OS build 16299.1565)
reason-vscode: 1.7.5

I installed and configured ```reason-vscode``` as specified in https://github.com/jaredly/reason-language-server#onivim, i.e. I have added the following to onivim configuration file,
```
"language.reason.languageServer.command": "c://rls//reason-language-server.exe",
"language.reason.languageServer.arguments": [],
"language.reason.languageServer.configuration": {},
```
I launch oni2 from ```c:\Users\user1\source\proj1``` and try to edit ```.re``` file. 

I get error message as below,

Error message: Reason Language Server not found! c:\Users\user1\source\proj1\c:\Program Files\Onivim2\rls.exe

It seems onivim is trying to look in to a folder which is a appending of current folder + c:\Program Files\Onivim2\rls.exe. Is this reason-vscode issue perhaps?

**Comment by CrossR** [comment] 2020-01-28 15:07
Confusingly, I think those instructions are for Oni1!

We bundle rls to my knowledge, so you shouldn't need to download anything to get it working, so I think you are bumping into #1080.

**Comment by glennsl** [comment] 2020-03-25 12:40
FYI, #1457 added support for ocaml-lsp-server, which works like a charm on Linux, and probably works better on Windows as well.

Anyway, I'm closing this as I understand it's essentially a duplicate of #1080.

**Closed by glennsl** 2020-03-25 12:40 UTC
Labels: A-extension, A-technical, bug, duplicate, platform-windows
