### ISSUE TITLE
Initial results in ´Ctrl+P´ menu not deterministic.

### ISSUE THREAD

**Issue by m-kru** [onivim/oni2#818] opened 2019-10-05 14:53 UTC
~~1. When I navigate with down arrow key below the position of last entry in the list I can't navigate with arrow keys anymore.~~ Edit: Fixed in #894

2. I have pressed `CTRL + P` few times in the Oni2 repository, I have get different results. It looks like the behavior is not deterministic. The order or result looks like it is random. I did not realize any period.

![p6](https://user-images.githubusercontent.com/26227737/66256669-8093fd80-e790-11e9-9a7a-718e32804418.png)
![p5](https://user-images.githubusercontent.com/26227737/66256640-3f035280-e790-11e9-9ac5-c422b4270620.png)
![p4](https://user-images.githubusercontent.com/26227737/66256641-3f035280-e790-11e9-8e19-f12e4f1b6430.png)
![p3](https://user-images.githubusercontent.com/26227737/66256642-3f035280-e790-11e9-8d75-63c8258ffd67.png)
![p2](https://user-images.githubusercontent.com/26227737/66256643-3f9be900-e790-11e9-917f-6d8db779f22b.png)
![p1](https://user-images.githubusercontent.com/26227737/66256644-3f9be900-e790-11e9-8d40-e26336c6cd65.png)

**Comment by glennsl** [comment] 2019-10-10 14:35
FYI: I'm working on this as part of the menu renovation project.

**Comment by glennsl** [comment] 2019-10-30 18:04
The first issue was fixed in #894, and the second will be fixed in #914 I believe. But I'll close this out anyway as a duplicate of #911, since that's more specific.

**Comment by glennsl** [comment] 2019-10-31 20:16
Reopening, since this is actually a separate issue.

There seems to be two causes for this:

1. Ripgrep isn't asked to sort the results. This might be because sorting will be slower because it disables parallelism. This trade-off makes sense for workspace search, I think, but not so much for the Ctrl+P menu.

2. Ripgrep results are processed using a FIFO list, which means results will be reordered depending on how many "blocks" ripgrep puts in before the processing job pulls it out. I see no reason for not using a LIFO queue here instead.

**Closed** 2019-12-10 16:43 UTC
Labels: A-quickmenu, bug
