### ISSUE TITLE
macOS sidebar renders under window control buttons

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#1462] opened 2020-03-13 02:34 UTC
## What?
When the app is maximized (not fullscreen), the sidebar will render under the radio buttons.
<img width="1392" alt="Screen Shot 2020-03-12 at 21 28 26" src="https://user-images.githubusercontent.com/10119394/76583935-88c33800-64a8-11ea-88a7-ae019afacb4f.png">

## Installation details
macOS 10.14.6
Onivim2 0.3.0 6293fb2c – Installed from early-access portal

## Notes
The top bar also seems to disappear when the screen is maximized. Seen here when window size is sub-max. It seems the positioning of the sidebar is flowing and when the top element isn't there its position isn't relatively set from the top.
<img width="1392" alt="Screen Shot 2020-03-12 at 21 32 34" src="https://user-images.githubusercontent.com/10119394/76584205-42baa400-64a9-11ea-8c52-fb4822ad60af.png">

**Comment by glennsl** [comment] 2020-03-13 08:32
Partial duplicate of #1379, but this is more accurate and has more information

**Comment by zbaylin** [comment] 2020-05-12 20:14
This bug is due to different operating systems having different definitions of what it means to be "maximized". Right now we only render the macOS titlebar if the window is not maximized, but what we really want is for the window not to be fullscreen. I created a PR in `reason-sdl2` to address this by adding a `Window.isFullscreen` function.

Should be fixed (relatively) soon! Sorry about that!

**Comment by bryphe** [comment] 2020-05-15 18:51
I think we have the APIs now to be able to fix this, thanks to https://github.com/revery-ui/reason-sdl2/pull/74 !

**Closed** 2020-05-20 01:16 UTC
Labels: A-workspace, U-revery, bug, platform-macos
