### ISSUE TITLE
ChromeOS support

### ISSUE THREAD

**Issue by chimon2000** [onivim/oni2#781] opened 2019-09-24 18:19 UTC
When attempting to use on Chrome OS, the font size is painfully small.

![image](https://user-images.githubusercontent.com/6907797/65538905-5875e600-ded6-11e9-91d7-94f988f8ec1f.png)

I had the same issue with Sublime Text until the most recent update so maybe it's a related issue.

**Comment by szbergeron** [comment] 2019-09-24 18:26
Unfortunately there are some blockers for auto-detecting scaling on Linux (including for Linux apps on Chrome OS), but you should be able to manually work around this somewhat by changing editor.fontSize in settings. UI scaling is seemingly working properly with revery on sdl, and some Skia integration will help here as well, but it's still somewhat of a WIP feature.

**Comment by bryphe** [comment] 2019-09-26 21:19
Thanks for logging the issue @chimon2000 !

I believe this is the same root cause as #526 . 

We're working on some changes in Revery to properly respect the GTK scaling via the `GDK_SCALE` environment variable: https://github.com/revery-ui/revery/pull/555

In this case, we'd use the following to figure out the right 'scaling' on Linux:
- `--force-device-scale-factor` CLI flag
- `GDK_SCALE` environment variable

**Comment by CrossR** [comment] 2019-10-23 21:51
What is the status of this now, since the updates to scaling have gone in?

**Comment by bryphe** [comment] 2020-08-18 01:15
I'll close this out as resolved with the scaling fixes - #793 #1069 #1206 - let us know if you're still seeing this, though!

**Closed by bryphe** 2020-08-18 01:15 UTC
Labels: A-technical, I-daily-editor-blocker, S-duplicate, U-revery, bug, platform-other
