### ISSUE TITLE
Autocomplete directories with slash at the end.

### ISSUE THREAD

**Issue by m-kru** [onivim/oni2#814] opened 2019-10-05 11:34 UTC
For example, I want to execute vim edit command so I type `:e /ho`:
![home1](https://user-images.githubusercontent.com/26227737/66254293-b2976680-e774-11e9-9f77-36f85d2d319f.png)
after hitting tab I get `:e /home`:
![home2](https://user-images.githubusercontent.com/26227737/66254299-bb883800-e774-11e9-83fd-a389316e37e5.png)

I wish I get `:e /home/`.
It reduces typing and is compatible with vim.

**Comment by glennsl** [comment] 2019-10-05 17:44
This seems like a duplicate of #754

**Comment by bryphe** [comment] 2019-10-05 18:46
I'll resolve this as a duplicate - if you could '+1' #754 , that would be helpful in our prioritization!

**Closed** 2019-10-05 18:47 UTC
Labels: duplicate, enhancement
