### ISSUE TITLE
Vim general usage

### ISSUE THREAD

**Issue by jirmonder** [onivim/oni2#2169] opened 2020-07-23 19:10 UTC
Hi guys, love all the hard work on making onivim2 a reality

At the moment i'm using onivim2 v0.4.0

Can't seem to select text inside quotes with vim commands like v+i+' or v+a+' also no support for this same movement with tags.

**Comment by mabuchner** [comment] 2020-07-24 01:09
Duplicate of #1880.

**Comment by bryphe** [comment] 2020-07-24 01:19
Thanks for logging the issue @jirmonder (and thanks @mabuchner for finding the duplicate issue!)

Will use #1880 to track - I'll be taking a pass over these in the next milestone (focusing on Vim improvements)

**Closed by bryphe** 2020-07-24 01:19 UTC
Labels: A-vim, R-duplicate
