### ISSUE TITLE
allow split resizing with tmux-style ctrl-w+{hjkl}

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1643] opened 2020-04-20 11:31 UTC
It would be great to be able to resize splits in a way similar to the tmux way. I.e.:

Ctrl-w+{hjkl}, i.e.:

    press ctrl and keep it pressed all the way
    press w
    pressing {hjkl} moves the border of the splits

(note: this would complement nicely the already implemented:

    press crtl
    press w
    release crtl
    press {hjkl} to move between splits)

**Comment by glennsl** [comment] 2020-04-20 13:44
Closing as duplicate of #463. You might want to upvote and leave a comment there though.

**Comment by glennsl** [comment] 2020-06-05 12:59
Reopening since these specific keybindings haven't been implemented yet.

**Comment by glennsl** [comment] 2020-06-11 20:29
This has been implemented in #1919. No default keybindings have been added as they conflict with the default vim behaviour, but you can add bindings for these yourself:

https://github.com/onivim/oni2/pull/1919/files#diff-02f8653c8da88daa1ded35ad30138b18R539-R624

**Closed** 2020-06-12 13:59 UTC
Labels: A-workspace, I-daily-editor-blocker, enhancement
