### ISSUE TITLE
Bug: Tabs in a line mess up cursor and text placement

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#1237] opened 2020-01-21 03:36 UTC
01/21/2020
## Setup

1) In the `.config/oni2/configuration.json` file, have the following setup:
```
"editor.insertSpaces": true,
"editor.indentSize": 2,
"editor.tabSize": 2,
```
2) Open a file and add some text. Insert tabs at the front of some lines. You would need to use a template that has tabs since the “editor.insertSpaces” is set to true.
3) Try to edit inside a line with tabs at the front and then lines without.

BTW: I just rebuilt Oni2 and it is still there.

## What happens

When you edit lines without tabs, everything goes okay. When I edit lines with tabs, the cursor position is not the same as the edit position. This makes editing impossible. I have to strip all tabs off first. I use a lot of templates that have tabs, so this comes up quit often.

**Comment by bryphe** [comment] 2020-01-23 23:09
Thanks for logging the issue @raguay !

This is definitely a bad issue - the root cause is that we are not accounting for the 'tab size' in certain cases. https://github.com/onivim/oni2/pull/1224 will help consolidate the logic for this (so that `IndentationSettings` are tied to the Buffer, and don't need to be passed around dependently) - and then I'll look at this on top of that.

**Comment by raguay** [comment] 2020-01-24 04:42
Glad to help. Let me know when it’s being worked on so that I can thoughly test it. I’m using Oni2 everyday in my workflow, so testing is easy.

**Comment by bryphe** [comment] 2020-02-08 14:59
This should actually be fixed now with https://github.com/onivim/oni2/pull/1224, @raguay (sorry, I just realized I hadn't updated this issue). As part of that PR, the calculations for character width were corrected to account for tab size. 

Let me know if you still see any issues in the latest builds.

**Comment by raguay** [comment] 2020-02-09 02:15
Hi,

Yes, I just compiled and tested. It is working great now. Thanks!

Richard

**Closed** 2020-02-09 02:17 UTC
Labels: A-editor-component, I-daily-editor-blocker, bug
