### ISSUE TITLE
Endless loop hangs Onivim on macOS 10.15.6 when opening main.go

### ISSUE THREAD

**Issue by dsincl12** [onivim/oni2#2269] opened 2020-08-08 08:31 UTC
When I select the attached main.go file, Onivim hangs in an endless loop. The debug output is:

[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"crypto/aes" at byte offset 0
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"crypto/aes" at byte offset 0
[DEBUG]    +0ms Revery.FontCache : Resolving fallback for: 	"crypto/aes" at byte offset 0

which goes on forever until I force quit the application.

[main.txt](https://github.com/onivim/oni2/files/5044949/main.txt) -> rename to main.go

**Comment by CrossR** [comment] 2020-08-08 09:05
Hi!

What version of Oni2 was this on, and what OS?
There was a bunch of fixes for this exact issue recently, so if its a build that is a few days old it could be missing those fixes. Or its possible the fixes missed an edge case...

On mac with the latest release it looks fine, though it is very strange its trying to resolve a fallback for `crypto/aes`, when its just normal letters, so its possible soemthing different is happening here.

**Comment by dsincl12** [comment] 2020-08-08 09:25
First try was the latest version available for download. Then I cloned the repo and built everything just to check if it had been fixed already. OS is in the title, macOS 10.15.6.

**Comment by CrossR** [comment] 2020-08-08 11:52
Could you upload the full log file from launch to the start of the endless loop? May want to do a search replace of your username etc, but apart from paths there shouldn't be anything identifying in there. A gist is usually the best way to upload them since they get longer.

I'm not able to repro on macOS 10.14 and I'd be surprised if it was an issue specific to 10.15, so I'm thinking maybe its an issue loading the font file entirely or something, so the fallback fails and the default loading also fails causing issues.

**Comment by dsincl12** [comment] 2020-08-08 11:55
The application only ran for a few seconds but the log file is 150MB+. I'll truncate the file during the day and make a gist with the contents.

**Comment by dsincl12** [comment] 2020-08-08 13:38
https://gist.github.com/dsincl12/3eb2f7bda113fd398ecfd14ddab58118

Could it have something todo with the JetBrains Mono font? I have JetBrains Rider installed.

**Comment by dsincl12** [comment] 2020-08-08 13:52
Removed the JetBrains Mono font and now everything works. So now we at least know what the problem is :)

**Comment by zbaylin** [comment] 2020-08-08 15:38
@dsincl12 Are you able to post your config file when the crash was still happening? Should help clear some things up for us. Thanks!

**Comment by dsincl12** [comment] 2020-08-08 16:11
```
{
  "workbench.colorTheme": "One Dark Pro",
  "editor.minimap.enabled": true,
  "editor.insertSpaces": false,
  "editor.indentSize": 4,
  "editor.tabSize": 4,
  "editor.DetectIndentation": true,
  "editor.LargeFileOptimizations": true,
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.showSlider": true,
  "editor.minimap.maxColumn": 120,
  "editor.lineNumbers": "on",
  "editor.insertSpaces": false,
  "editor.indentSize": 4,
  "editor.tabSize": 4,
  "editor.fontSize": 12,
  "editor.renderIndentGuides": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.renderWhitespace": "all",
  "editor.autoClosingBrackets": "LanguageDefined",
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.iconTheme": "vs-seti",
  "files.exclude": [ "_esy", "node_modules" ],
  "editor.zenMode.hideTabs": true,
  "go.useLanguageServer": true
}

**Comment by dsincl12** [comment] 2020-08-08 17:13
Just to make it clear, I uninstalled the JetBrains Mono font from macOS and did _not_ have a font family set in my configuration file.

**Comment by bryphe** [comment] 2020-08-08 20:10
Thanks for all the details, @dsincl12 ! I'm able to reproduce by installing the Jet Brains Mono font from here, system wide: https://www.jetbrains.com/lp/mono/#how-to-install - and then opening that file with Onivim 2 w/ no `editor.fontFamily` set.

Based on the heaviest stack trace from the hang: 
```
Heaviest stack for the main thread of the target process:
  75  camlHarfbuzz__hb_shape_inner_357 + 143 (Oni2_editor + 3665535) [0x10f754e7f]
  65  rehb_shape + 753 (harfbuzz.cpp:155,9 in Oni2_editor + 6693073) [0x10fa380d1]
  64  hb_shape + 78 (hb-shape.cc:139,19 in Oni2_editor + 7326798) [0x10fad2c4e]
  64  hb_shape_plan_execute + 235 (hb-shaper-list.hh:42,1 in Oni2_editor + 7325675) [0x10fad27eb]
  63  _hb_ot_shape + 4462 (hb-ot-shape.cc:250,9 in Oni2_editor + 7284686) [0x10fac87ce]
  63  hb_ot_map_t::substitute(hb_ot_shape_plan_t const*, hb_font_t*, hb_buffer_t*) const + 138 (hb-ot-layout.cc:1899,3 in Oni2_editor + 7026218) [0x10fa8962a]
  5   void hb_ot_map_t::apply<GSUBProxy>(GSUBProxy const&, hb_ot_shape_plan_t const*, hb_font_t*, hb_buffer_t*) const + 714 (hb-ot-layout.cc:1871,20 in Oni2_editor + 7027146) [0x10fa899ca]
  1   hb_buffer_t::message(hb_font_t*, char const*, ...) + 144 (hb-buffer.hh in Oni2_editor + 7026400) [0x10fa896e0]
```

This does similar to a couple other hangs we saw in the fallback code: https://github.com/revery-ui/revery/pull/970 https://github.com/revery-ui/revery/pull/974

**Comment by bryphe** [comment] 2020-08-08 21:12
Started a fix for this in revery: https://github.com/revery-ui/revery/pull/980

**Closed** 2020-08-10 21:56 UTC
Labels: A-font, I-crash, I-daily-editor-blocker, bug
