### ISSUE TITLE
Menus width does not scale.

### ISSUE THREAD

**Issue by m-kru** [onivim/oni2#822] opened 2019-10-06 06:02 UTC
![menu_w](https://user-images.githubusercontent.com/26227737/66265005-7a913180-e80f-11e9-8ffd-522d2956cc76.png)
 
I think it should scale with string width of move view to the right, so the the end of the string is visible.

**Comment by glennsl** [comment] 2019-10-06 08:04
Duplicate of #758

**Comment by CrossR** [comment] 2019-10-06 15:41
Thanks @glennsl !

**Closed by CrossR** 2019-10-06 15:41 UTC
