### ISSUE TITLE
Powershell terminal doesn't take keyboard input

### ISSUE THREAD

**Issue by haaland** [onivim/oni2#3098] opened 2021-02-05 07:44 UTC
:terminal opens a new powershell window, but it doesn't register any keyboard input. Trying 'i' to enter insert mode, doesn't work. 
Env: Windows 10 up to date. OniVim nightly 0.5.9. 
Note: this could be a duplicate, didn't check all previous issues.

**Comment by leonardootto** [comment] 2021-02-08 17:50
Same Here.
Windows 10, version 0.5.9 (9aa3b88c)

**Comment by bryphe** [comment] 2021-02-08 23:32
Thanks for logging the issue, @haaland - I was able to reproduce on latest `master`. 

I'm seeing this in the log:
```
[WARN]  [ 2.885s] Oni2.Extension.ClientStore : Unhandled message: (Msg.Errors
   (Msg.Errors.OnUnexpectedError
      `List ([`Assoc ([("$isError", `Bool (true));
                        ("name", `String ("Error"));
                        ("message",
                         `String ("This socket has been ended by the other party"));
                        ("stack",
                         `String ("Error: This socket has been ended by the other party\n\tat Socket.writeAfterFIN [as write] (net.js:456:14)\n\tat WindowsTerminal._doWrite (C:\\Program Files\\Onivim2\\node\\node_modules\\node-pty\\lib\\windowsTerminal.js:114:30)\n\tat WindowsTerminal._defer (C:\\Program Files\\Onivim2\\node\\node_modules\\node-pty\\lib\\windowsTerminal.js:156:24)\n\tat WindowsTerminal._write (C:\\Program Files\\Onivim2\\node\\node_modules\\node-pty\\lib\\windowsTerminal.js:111:14)\n\tat WindowsTerminal.Terminal.write (C:\\Program Files\\Onivim2\\node\\node_modules\\node-pty\\lib\\terminal.js:81:14)\n\tat TerminalProcess._doWrite (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\contrib\\terminal\\node\\terminalProcess.js:259:30)\n\tat TerminalProcess._startWrite (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\contrib\\terminal\\node\\terminalProcess.js:244:18)\n\tat TerminalProcess.input (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\contrib\\terminal\\node\\terminalProcess.js:237:18)\n\tat ExtHostTerminalService.$acceptProcessInput (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\api\\common\\extHostTerminalService.js:409:92)\n\tat RPCProtocol._doInvokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:341:27)\n\tat RPCProtocol._invokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:326:45)\n\tat RPCProtocol._receiveRequest (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:253:32)\n\tat RPCProtocol._receiveOneMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:181:26)\n\tat C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:65:52\n\tat Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:456:38)\n\tat BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:375:35)\n\tat C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\node\\extensionHostProcessSetup.js:145:41\n\tat Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:456:38)\n\tat BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:375:35)\n\tat PersistentProtocol._receiveMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:651:41)\n\tat C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:510:83\n\tat Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:456:38)\n\tat ProtocolReader.acceptChunk (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:189:37)\n\tat C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:158:61\n\tat Socket.listener (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\node\\ipc.net.js:17:40)\n\tat Socket.emit (events.js:315:20)\n\tat addChunk (internal/streams/readable.js:309:12)\n\tat readableAddChunk (internal/streams/readable.js:284:9)\n\tat Socket.Readable.push (internal/streams/readable.js:223:10)\n\tat Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"))
                        ])
               ])))          
```

It looks like our `pty` session is closing unexpectedly upon receiving input - looking into it

**Comment by bryphe** [comment] 2021-02-08 23:59
May be related to this: https://github.com/microsoft/node-pty/issues/457 (and the upgrade of node  to 14 LTS in #3012 )

**Comment by haaland** [comment] 2021-02-09 12:23
Yes. Thanks for looking into it this fast. Loving OniVim and really want it in a workable state. Hoping to find time to contribute in the future. Reason syntax looks really nice, F# like.

**Closed** 2021-02-09 22:15 UTC
Labels: A-terminal, I-daily-editor-blocker, bug, platform-windows
