### ISSUE TITLE
Feature - multiple oni2 windows

### ISSUE THREAD

**Issue by mdnmdn** [onivim/oni2#2856] opened 2020-12-17 21:27 UTC
Should be very useful to open multiple oni2 windows in order to work on multiple projects / folder at the same time

**Comment by bryphe** [comment] 2020-12-21 22:37
Thanks for logging the issue, @mdnmdn !

I think this might be a duplicate of #2589 - I'll close it out as a duplicate, but let me know if #2589 doesn't capture what you had in mind.

**Closed by bryphe** 2020-12-21 22:37 UTC
Labels: A-other, R-duplicate, enhancement
