### ISSUE TITLE
Features: Completion navigation, Symbols outline

### ISSUE THREAD

**Issue by pikachunakapika** [onivim/oni2#2002] opened 2020-06-25 00:44 UTC
Hi all,

thanks for your work!

I wonder if I can navigate the completions with arrow keys UP and DOWN or is this not desired because of vim legacy?

Also I would like to have a symbol outline panel (maybe on the right side).

While checking the sources I saw that there already is a symbol menu so maybe some of this can be reused?

Thx for your work and all the best!

Best Regards
Massl

**Comment by bryphe** [comment] 2020-06-25 01:02
> I wonder if I can navigate the completions with arrow keys UP and DOWN or is this not desired because of vim legacy?

Hmm, good question - I don't see any reason to restrict this - I think it would be natural to include UP / DOWN as well.

> Also I would like to have a symbol outline panel (maybe on the right side).

Yes, this would be really cool! We have the ext host API wired up... but need to build the UI around it. 

A related issue is https://github.com/onivim/oni2/issues/1740 (maybe there'd be a way to surface the symbols on the minimap, too 🤔 )

**Comment by pikachunakapika** [comment] 2020-06-25 01:07
Oh that would be super nice. We could use the minimap for all of this. But I think it might be a challenge to make both work in the same UI.

**Comment by bryphe** [comment] 2020-11-25 22:18
FYI, we actually have both of these now:
1) `Down` and `Up` work with completion
2) The symbol explorer is in the same pane as the file explorer (just collapsed by default). You can use the `gO` command in normal mode (goto-outline) to focus it. Just needs language support to populate it (the outlines in the gif are from the ocaml-lsp extension)

Quick demo:
![symbol-explorer2](https://user-images.githubusercontent.com/13532591/100287108-e9a47a80-2f28-11eb-82f5-c4309c1dfe75.gif)

So I believe this is now fixed :+1:

**Comment by pikachunakapika** [comment] 2020-12-03 22:50
Wow! Really great work!

**Comment by likern** [comment] 2021-03-13 15:49
@bryphe How to reveal symbols in editor when navigating over symbols in `Symbol Outline` panel?

While `gO` is working for Typescript files and I can see `Outline` panel filled up with symbols, navigating over these  symbols do nothing.

- [ ] `j` `k` are working for navigating in `Outline` panel
- [ ] Navigating over symbols doesn't show them in editor (`Outline` becomes useless)
- [ ] Neither `Enter` | `Space` | `Tab` | `Escape` working to show symbols in editor
- [ ] Clicking on symbol manually using **mouse works** (show them in editor)

**Comment by bryphe** [comment] 2021-03-16 23:08
Thanks @likern , good question - looks like there was a regression in this functionality. Looking into it in #3290

**Closed** 2021-03-17 16:01 UTC
Labels: A-extension, A-workspace, enhancement
