### ISSUE TITLE
Alt+Tab introduces a new Tab character

### ISSUE THREAD

**Issue by dsejas** [onivim/oni2#828] opened 2019-10-07 20:47 UTC
**Description:** When pressing Alt+Tab to change to another window, Oni introduces a new TAB character in INSERT mode.
**Version:** #6ca3646b; dated October 6th, 2019.
**How to reproduce:** Open Oni2, press `i` in order to enter INSERT mode, then press Alt+Tab to go to another window, return to Oni2's window and you will see a new TAB character has been added.

**Comment by bryphe** [comment] 2020-11-17 03:33
Just tried this on latest builds on Windows and Linux (Manjaro) - looks like it no longer reproduces (must've been fixed with some of the input improvements on the way). LMK if you still see it :+1:

**Closed by bryphe** 2020-11-17 03:33 UTC
Labels: A-input, A-technical, bug
