### ISSUE TITLE
When opening a single file from command line the left navigation bar does not open

### ISSUE THREAD

**Issue by anan44** [onivim/oni2#1523] opened 2020-03-30 08:32 UTC
I a single file is opened from command line like "oni2 myfile.txt" the editor does not open properly. It is possible to edit the file but the left navigation bar is completely missing. File explorer is missing but so are options for Search, Extensions and Source Control. 

If single file is opened the left command line should still be there.

**Comment by glennsl** [comment] 2020-03-30 08:46
This is intentional. You can turn this behaviour off by setting `editor.zenMode.singleFIle` to `false` in your configuration. See https://onivim.github.io/docs/configuration/settings.

I'll close this for now since it works as designed, but will take it into account when considering whether or not it should be the default for both the vscode and vim profiles when we get around to implementing that. Although if anyone has opinions on that, don't let issue being closed prevent you from airing them here.

**Closed by glennsl** 2020-03-30 08:46 UTC
Labels: A-configuration, A-workspace
