### ISSUE TITLE
Bug: Rendering bug when editing JSON

### ISSUE THREAD

**Issue by praveenperera** [onivim/oni2#585] opened 2019-08-04 21:51 UTC
When you edit a JSON file and try to add a new entry the other keys of the json file disappears.

See video: https://i.imgur.com/To2P44S.mp4

**Comment by CrossR** [comment] 2019-10-23 22:06
I think this was an issue with the old syntax highlighting, am I'm not able to reproduce now, so I'll close this out.

If its still happening, can open back up though!

**Closed by CrossR** 2019-10-23 22:06 UTC
Labels: bug, daily editor blocker
