### ISSUE TITLE
[Feature] Treat file explorer as split

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#2070] opened 2020-07-05 07:31 UTC
Hi, in my vim setup I'm using NERDTree ad it is just another split this mean I can go to it with `<C-W>h` and move in nodes by `hjkl`. I think it will be nice feature in Oni.

**Comment by CrossR** [comment] 2020-07-05 12:59
Closing as a duplicate of https://github.com/onivim/oni2/issues/528.

We are working towards adding this and have got some of the necessary bits in place for it now! If you have any input/suggestions after reading the linked issue, feel free to add them! Also don't forget to 👍 the issue since we use that to prioritise stuff, though that issue is already near the top I think.

**Closed by CrossR** 2020-07-05 12:59 UTC
