### ISSUE TITLE
Ctrl+Tab has no effect while in a Terminal window

### ISSUE THREAD

**Issue by barbu110** [onivim/oni2#1602] opened 2020-04-13 10:40 UTC
Opening a Terminal window (`:term ++curwin`) prevents <kbd>Ctrl</kbd> + <kbd>Tab</kbd> from working (i.e. switching to another buffer).

Steps to reproduce:
1. While having a buffer open, hit `:term ++curwin`
2. Hit <kbd>Ctrl</kbd> + <kbd>Tab</kbd>

**Comment by glennsl** [comment] 2020-04-13 10:45
Closing as duplicate of #1600 :wink: Thanks for the well-formed report though!

Also, fix incoming in #1601.

**Closed by glennsl** 2020-04-13 10:45 UTC
Labels: A-configuration, S-duplicate, bug
