### ISSUE TITLE
file explorer does not update automatically

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1887] opened 2020-06-06 18:56 UTC
The file explorer on the left does not update automatically. For example, if a new file appears or a file gets removed from a folder, it does not appear / disappears of the file explorer tree. I have to fold and unfold the corresponding folder for files contained in it to appear / disappear.

Any way to make sure the file explorer refreshes when needed?

**Comment by CrossR** [comment] 2020-06-07 10:15
Duplicate of https://github.com/onivim/oni2/issues/792.

Right now, there isn't a file system watcher hooked up, so any updates are not mirrored. We do have file system watchers available now, so we should be able to do this now at least.

**Closed by CrossR** 2020-06-07 10:15 UTC
