### ISSUE TITLE
Using command vim.esc for keybinding doesn't match expected <Esc> behavior

### ISSUE THREAD

**Issue by Towerism** [onivim/oni2#1509] opened 2020-03-27 17:20 UTC
The cursor stays in place rather than moving to the left by one character.

**Comment by Apostolique** [comment] 2020-03-28 05:43
Same issue as #1194.

**Comment by glennsl** [comment] 2020-03-28 08:59
Thanks @Apostolique. Closing as duplicate of #1194.

**Closed by glennsl** 2020-03-28 08:59 UTC
Labels: A-vim, U-libvim, bug, duplicate

**Comment by Towerism** [comment] 2020-03-28 12:03
This isn’t a duplicate @glennsl. Exiting by pressing esc from insert mode works as I expect. It’s the vim.esc that doesn’t work.

**Comment by glennsl** [comment] 2020-03-28 12:37
From the current description this still sounds like an exact duplicate, except it lacks some context like starting off in insert mode.

`vim.esc` just sends `<ESC>` to vim, so it's essentially the same thing. If it's an issue with a specific keybinding, rather than the command it invokes, we'll need to know what the actual keybinding is. It would also help to have more details about the specific action you're performing, the context (i.e. which mode etc.), what you expect and what actually happens in full, not just the defective behaviour.

**Comment by Towerism** [comment] 2020-03-31 20:18
{ key: "fd", command: "vim.esc", when: "insertMode || visualMode" }

Pressing ifd over and over again, the cursor remains in the same place (This is not #1194)

Pressing i<Esc> over and over again, the cursor moves back; occasionally the cursor will remain in place (This is #1194).

Reopen this issue because it is not the same as #1194.

**Comment by Towerism** [comment] 2020-03-31 20:39
This gif shows the two issues perfectly. As you can see in the gif, using vim.esc via keybinding fd does not move the cursor backwards ever. But the cursor moves back sometimes when pressing Esc directly.

![image](https://user-images.githubusercontent.com/2057426/78073024-bb54a800-7365-11ea-8292-7b2ab5b459c5.png)

**Comment by glennsl** [comment] 2020-04-01 12:46
Thanks for the detailed information! This still seems like the same issue though. The incorrect behaviour is exactly the same apart form occurring more frequently with your keybinding. That is still very valuable diagnostic information however, so it would be great if you could post it directly in #1194. Unless of course you still think there's a categorical difference that makes this a separate issue. But then you have to explain the difference to me.

**Comment by Towerism** [comment] 2020-04-01 16:06
I don't know if there is a categorical difference, since I don't how oni works internally. I believe it has more to do with the way oni handles chords, since the same behavior of `fd` occurs when I press `f<Esc>`.

**Comment by glennsl** [comment] 2020-04-01 17:37
Could be, though I suspect there's still the same timing issue at the root of this, but that the chording, or something related to it, exacerbates the problem.

@bryphe, since you know the ins and outs of the chording, do you want to chime in? Even if it has the same root cause, there could be a problem with the chording that triggers other timing-sensitive bugs as well, so might be a good idea to look at this separately anyway.
