### ISSUE TITLE
running `oni2 filename` twice in the CLI opens two instances of Onivim2

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#3058] opened 2021-01-28 03:46 UTC
Running `oni2 filename1` and then `oni2 filename2` in the CLI opens two instances of Onivim2.

I would expect this to open them in two windows in the one instance of Onivim2, as already happens when you run `on2 filename1 filename2`.

**Comment by kinglouie** [comment] 2021-01-29 11:46
duplicate of #2617, #1250
related #2947

**Comment by bryphe** [comment] 2021-01-30 00:14
Definitely... I need to create a ReasonML version of a library like this for Onivim: https://github.com/pierrefourgeaud/node-single-instance#read

And a socket like this:https://github.com/pierrefourgeaud/node-single-instance/blob/2d108db5ae0f964b6e74fa1c830489992d4013eb/index.js#L16

Would solve a bunch of problems (allowing us to handle the multi-instance case, as well as opening a file from the embedded terminal in the running instance of Onivm)

**Closed** 2021-04-30 20:10 UTC
Labels: A-cli, S-duplicate, bug
