### ISSUE TITLE
Integrated Terminal not Rendering when Opened in new Window

### ISSUE THREAD

**Issue by Cy-Tek** [onivim/oni2#1494] opened 2020-03-23 14:09 UTC
When I open a new terminal with either of the split-view options everything works correctly and I see proper rendering as shown below

![image](https://user-images.githubusercontent.com/16470547/77324807-b18bce80-6ced-11ea-8277-88c178ce4d9c.png)

But when I use the **Terminal: Open terminal in new window** option I get a weird behaviour where the terminal will open, but it won't render the characters, only the cursor. It accepts input too, and the commands do work, but you cannot see any output.

![image](https://user-images.githubusercontent.com/16470547/77325127-265f0880-6cee-11ea-91fe-1f29771d939e.png)

I only have a windows machine, so I cannot verify whether this occurs on other platforms as well, but it at least happens on Windows 10.

This was confirmed by @CrossR on GitHub

**Comment by CrossR** [comment] 2020-03-23 15:11
I've confirmed this on Mac as well. Oddly, it does load if I open up a second terminal.

That is:
 - Open terminal in current window -> No rendered terminal. 
 - Open second terminal in a vertical/horizontal split -> Split one appears fine, but also the current window one loads correctly as well. I can see they are different terminals as my bash prompt contains the time to the second and the times in each split are different.

If I open a second terminal in the current window, it still fails to load.

**Comment by bryphe** [comment] 2020-03-31 17:39
This should be fixed by #1531 (same root cause as #1461 )

**Closed by bryphe** 2020-03-31 17:40 UTC
Labels: A-terminal, bug
