### ISSUE TITLE
Vim multiline does not work

### ISSUE THREAD

**Issue by kchuangk** [onivim/oni2#1448] opened 2020-03-09 05:52 UTC
In vim, typing <C-v> start a multi-line edit at the same point and <I> begins insert at the cursor. It doesn't work in onivim2.

https://vim.fandom.com/wiki/Inserting_text_in_multiple_lines

https://stackoverflow.com/questions/9549729/vim-insert-the-same-characters-across-multiple-lines

**Comment by glennsl** [comment] 2020-03-09 09:02
Unless I've misunderstood, this is a duplicate of #288. Might still be worth keeping open for the additional search words though?

**Comment by glennsl** [comment] 2020-03-25 12:08
Closing this in favor of #288 as closed issues are still searchable, and this issue is also referenced from #288, because I've mentioned it three times now just to make sure ;)

**Closed by glennsl** 2020-03-25 12:08 UTC
Labels: A-editor-component, A-vim, U-libvim, duplicate, enhancement
