### ISSUE TITLE
Only show buffers for current tab in the tab bar.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni2#3602] opened 2021-05-26 23:38 UTC
Possibly a #goodfirsttask
In this screenshots there's two "tabs" (which are really workspaces) which are shown at the bottom.
Each tab has one buffer open. But the top "buffer bar" shows all the buffers across all tabs. I think it could be easy to just only show the buffers associated with the current tab at the top of the screen. I'm not sure there's too many reasons to use "tabs" in Oni but in case someone stumbles upon it, my suggested improvement would allow them to discover "oh tabs are at the bottom, and are more like workspaces, and buffers (which are more like tabs) are at the top".

<img width="798" alt="Screen Shot 2021-05-26 at 4 35 29 PM" src="https://user-images.githubusercontent.com/977348/119744268-7d0b2980-be40-11eb-9906-6bc181d6bec2.png">

**Comment by kinglouie** [comment] 2021-05-27 06:31
This seems to be a regression, because it was as you suggest when the tab feature was introduced. Keep in mind that this is basic vim functionality and in vim tabs are what you call workspaces and buffers are what other editors call tabs.

**Comment by bryphe** [comment] 2021-06-04 22:43
Might be related to #3150

**Comment by bryphe** [comment] 2021-07-09 21:28
Looks like this should also be fixed by #3755

**Closed by bryphe** 2021-07-09 21:28 UTC
Labels: A-tab-pages, A-vim, bug
