### ISSUE TITLE
Menu not reacting (on Windows 10)

### ISSUE THREAD

**Issue by riedel** [onivim/oni2#3108] opened 2021-02-07 09:55 UTC
On Windows  OniVim Version 0.5.9 (e0f353d1) does not react at all when selecting menu items  (clicking with mouse) .

Invoking items via shortcuts (those that have), works for me.

The only exception seems the Edit -> Undo and Edit -> Redo entry, which works as expected

**Comment by bryphe** [comment] 2021-02-09 00:53
Thanks for reporting, @riedel - I'm able to reproduce this on OSX as well as Windows.

Looks like  this is related to #3055 , which was partially reverted in #3084 - however, one of the changes was missed relating to the menubar, which broke the command execution.

**Comment by bryphe** [comment] 2021-02-09 21:58
Fixed now with #3118

**Closed by bryphe** 2021-02-09 21:58 UTC
Labels: A-workspace, I-daily-editor-blocker
