### ISSUE TITLE
Using Tab inserts an odd character

### ISSUE THREAD

**Issue by Luke-Argosino** [onivim/oni2#2477] opened 2020-09-18 23:18 UTC
<img width="802" alt="Screen Shot 2020-09-18 at 3 35 05 PM" src="https://user-images.githubusercontent.com/47580376/93652351-94e50080-f9c9-11ea-8838-aad0e6f2e38c.png">

When I try to tab on the Vim command line, it inserts a weird character as seen above. I am on MacOS and on the US keyboard layout. My version is 10.15.6. I've tried installing both the nightly build, and stable build. Something odd to note is that I wiped my MacBook recently, and that made this issue arise. Before reinstalling macOS, it worked fine. I tried to install all my other programs again to no avail.

[log.zip](https://github.com/onivim/oni2/files/5248601/log.zip)

Above is my attached logs. To generate the logs, I booted up Onivim and pressed ":[tab][tab}"

**Comment by raw-bin** [comment] 2020-09-21 11:12
To add to @Luke-Argosino's report: I can confirm that I see the same issue on my Mac running the latest macOS Catalina. Unlike @Luke-Argosino's situation, I saw the problem ever since I first installed onivim2. 

I assume that pressing tab while in the command line dialogue provides autocompletion. If so, we're missing that convenience. Happy to provide any diagnostic information. Thanks!

**Comment by Speykious** [comment] 2020-09-21 16:36
I use Linux Manjaro and I had the exact same issue with what looks like the exact same character.
I installed Onivim 2 from source a few hours ago.

**Comment by nathanKramer** [comment] 2020-09-22 02:39
I have the same issue.
Here is what seems to be a relevant part from the log:

points of interest

- "got 0 completions."
- "Resolving fallback for: :cd app	 at byte offset 7" (resolving a fall back character for a hard-tab)

```
[INFO]     +0ms Oni2.Store.dispatch : dispatch: KeyboardInput {isText = false; input = "<TAB>"}
[DEBUG]    +0ms Oni2.Store.dispatch : After: KeyboardInput {isText = false; input = "<TAB>"}
[INFO]     +0ms Oni2.Store.dispatch : dispatch: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "<TAB>")))
[DEBUG]    +0ms Oni2.Store.dispatch : After: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "<TAB>")))
[INFO]     +0ms Oni2.Store.dispatch : dispatch: (SignatureHelp (KeyPressed ((Some "<TAB>"), true)))
[DEBUG]    +0ms Oni2.Store.dispatch : After: (SignatureHelp (KeyPressed ((Some "<TAB>"), true)))
[DEBUG]    +0ms Oni2.Store.StoreThread : Running effect: Batch:
 vim.input

[INFO]     +0ms Oni2.Store.dispatch : dispatch: (QuickmenuCommandlineUpdated ("cd app\t", 7))
[DEBUG]    +0ms Oni2.Store.dispatch : After: (QuickmenuCommandlineUpdated ("cd app\t", 7))
[DEBUG]    +0ms Oni2.Store.Vim : checkCommandLineCompletions
[DEBUG]    +0ms Oni2.Store.Vim :   got 0 completions.
[INFO]     +0ms Oni2.Store.dispatch : dispatch: (QuickmenuUpdateFilterProgress (<opaque>, Complete))
[DEBUG]    +0ms Oni2.Store.dispatch : After: (QuickmenuUpdateFilterProgress (<opaque>, Complete))
[INFO]     +0ms Oni2.Store.dispatch : dispatch: Editor {scope = (EditorScope.Editor 0); msg = (ScrollToLine 0)}
[DEBUG]    +0ms Oni2.Store.dispatch : After: Editor {scope = (EditorScope.Editor 0); msg = (ScrollToLine 0)}
[INFO]     +0ms Oni2.Store.dispatch : dispatch: Editor {scope = (EditorScope.Editor 0); msg = (ScrollToColumn 7)}
[DEBUG]    +0ms Oni2.Store.dispatch : After: Editor {scope = (EditorScope.Editor 0); msg = (ScrollToColumn 7)}
[INFO]     +0ms Oni2.Store.dispatch : dispatch: Editor {scope = (EditorScope.Editor 0); msg = (CursorsChanged <opaque>)}
[DEBUG]    +0ms Oni2.Store.dispatch : After: Editor {scope = (EditorScope.Editor 0); msg = (CursorsChanged <opaque>)}
[DEBUG]    +0ms Oni2.Store.Vim : handled key: <TAB>
[DEBUG]    +0ms Oni2.Store.StoreThread : Effect complete: Batch:
 vim.input

[DEBUG]    +0ms Oni2.Store.StoreThread : Effect complete: Batch:
 input.immediateDispatch

[DEBUG]    +0ms Revery.App : Upshifting into active state.
[DEBUG]    +7ms Revery.FontCache : Resolving fallback for: :cd app	 at byte offset 7
```

Happy to send someone the full log file if helpful, but I'd rather not put it here since I'm not sure what info about my system might be in them (it's 11k lines)

**Closed** 2020-09-22 22:39 UTC
Labels: A-vim-cmdline, bug
