### ISSUE TITLE
[NOT A BUG] Forgot my license key.

### ISSUE THREAD

**Issue by karambaq** [onivim/oni2#1741] opened 2020-05-11 15:54 UTC
Hello guys, I've purchased early access while back and license key email went to the spam folder, I've accidentally clear all of my spam a few months ago, and now I remember about oni2, Idk is it to possible to restore by my email?

Thank you.

**Comment by CrossR** [comment] 2020-05-11 17:21
We don't have an automatic process right now unfortunately, but @bryphe can look it up for you based on your email.

Its probably easiest to do that on either twitter (https://twitter.com/bryphe), or discord (https://discord.com/invite/7maEAxV), so if you drop a message on either of those we should be able to sort it out. If you don't have either of them, you could drop an email, though I don't know the address of the top of my head.

May also be worth looking to see if it did get moved out of the spam, it'll probably be in an "outrunlabs" email.

**Comment by bryphe** [comment] 2020-05-11 17:47
For sure, we'll get it straightened out for you @karambaq ! You can feel free to e-mail me directly at bryphe@outrunlabs.com, too 👍

**Comment by bryphe** [comment] 2020-05-11 17:47
I'll close this out since it's a not a bug - but feel free to post here again if you're not able to reach on any of those channels.

**Closed by bryphe** 2020-05-11 17:47 UTC
Labels: A-other, question
