### ISSUE TITLE
Enter key at end of line acts as a backspace and deletes last character, have to type the last character again

### ISSUE THREAD

**Issue by ly-swanandkriyaban** [onivim/oni2#3191] opened 2021-02-26 19:32 UTC
Typing python BTW. I have not tested with other file types

Whenever I finish typing my code line and press Enter to go to the next line, the last character in the line gets eaten. I have to re-enter the character

Windows 10
2.0.5.1929

**Comment by bryphe** [comment] 2021-02-26 21:07
Hi @ly-swanandkriyaban ,

Thanks for logging the issue - that's a bad one.

I'm trying to reproduce - I'm not able to reproduce with the default configuration (tested on English and English International keyboard layouts, on both OSX and Windows):
![2021-02-26 12 58 54](https://user-images.githubusercontent.com/13532591/109354922-5cc4d200-7833-11eb-9b05-0822017ad57c.gif)

Some extra info might help to narrow this down:
1) What keyboard layout are you using? English, English International, or another?
2) Does it reproduce consistently, for every single line you press 'Enter'? Or only sometimes?
3) Do you have any custom keybindings?
4) Do you have any custom configuration (ie, a modified `"experimental.viml"`)?
5) Does the completion UI pop-up?

**Comment by ly-swanandkriyaban** [comment] 2021-02-26 21:11
1. US English keyboard (Thinkpad laptop)
2. Every line I enter
3. No custom keybindings - I just installed and started editing a .py (new) file
4. No custom config - I just changed the font size to 12 instead of the default 14
5. No it does not popup

**Comment by ly-swanandkriyaban** [comment] 2021-02-26 21:31
You can find a screen recording of this at https://1drv.ms/v/s!AmrgawBangv-h8Z21UPdGlTcOoDM2Q?e=aL8QdA

Hope that helps. I was fumbling around a bit, but at the end, you can see it happening twice

Thanks
Swanand

**Comment by bryphe** [comment] 2021-02-26 23:10
Hi @ly-swanandkriyaban ,

The video helps a ton - thanks for recording and uploading it! I did witness both instances of the bug 👍 

And with that, I'm now able to reproduce it consistently:
![2021-02-26 15 06 45](https://user-images.githubusercontent.com/13532591/109364784-69055b00-7844-11eb-9504-a76105c55d98.gif)

It's actually not Windows or Python specific - it's a bug with completion + auto-closing pairs. The completion UX _should_ close once the `"` or `)` are typed, but it erroneously stays active - and then pressing 'enter' engages the completion - but it's not doing the right thing (disregarding those auto-closing pairs).

I'm looking into a fix for this - in the meantime, a workaround is to add this to your configuration:
```
   "editor.acceptSuggestionOnEnter": false
```

**Closed** 2021-03-01 17:24 UTC
Labels: A-input, I-daily-editor-blocker, bug
