### ISSUE TITLE
commands ignored after hitting <ESC> for insert and block visual mode

### ISSUE THREAD

**Issue by irevived1** [onivim/oni2#1411] opened 2020-03-04 16:32 UTC
to repro the issue, in normal mode, do 10ia\<ESC\>
we are expected to see 'aaaaaaaaaa' in the editor, but currently we only get 'a' instead.  the 10 gets forgotten after hitting \<ESC\>

similarly in visual block mode.
example text:

lne1
lne2
lne3

in normal mode, cursor on first line do ^(Ctrl+v)jjAi\<ESC\>
expected output should be

line1
line2
line3

but got

lne1
lne2
lne3i

instead.

If this issue can be fixed then that would be great.  Thanks.

**Comment by massltoff** [comment] 2020-03-05 22:05
Same issue #809

**Comment by glennsl** [comment] 2020-03-25 12:11
Closing as duplicate of #809. Since it's referenced there, the additional information given here isn't lost.

**Closed by glennsl** 2020-03-25 12:11 UTC
Labels: A-vim, U-libvim, bug, duplicate
