### ISSUE TITLE
Code folding does not work

### ISSUE THREAD

**Issue by ArthurZ** [onivim/oni2#1868] opened 2020-06-03 03:18 UTC
I can't place a custom fold by marking a text with say `ma` and navigating away. Then applying `zf'a` to fold to the mark `a`.
I expect it to fold, which happens if I use Vim or Neovim. But not in OniVim.

**Comment by glennsl** [comment] 2020-06-03 07:20
Closing as duplicate of #1565.

**Closed by glennsl** 2020-06-03 07:20 UTC
Labels: A-editor-component, A-vim, S-duplicate, U-libvim, bug

**Comment by thomas-haslwanter** [comment] 2020-08-02 21:28
I don't understand why that issue is closed: Ver 0.4 (from end of June) still does not seem to support folding:
i) I have an indented text
ii) I have "set foldmethod=indent"
iii) now "zM" should close the fold ... but it doesn't

**Comment by CrossR** [comment] 2020-08-02 21:34
This issue is closed as issue #1565 is being used to track this issue instead! Duplicated issues makes it harder for us to keep track of stuff, so we close out ones that are duplicated.
