### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by Apostolique** [onivim/oni2#261] opened 2019-04-19 02:12 UTC
You can write a bunch of space, then press enter, or `o` in normal mode.

![image](https://user-images.githubusercontent.com/2766423/56401479-09d96700-6227-11e9-8403-c7f5f5df8017.png)

Oni2 tries to preserve the amount of indentation but uses tabs instead of spaces.

(6 spaces of indentation become 6 tabs on the next line.)

**Comment by maxdietrich** [comment] 2019-05-10 11:20
If I find time for it, I wanna take a look into why this happens this weekend.

**Comment by CrossR** [comment] 2019-05-10 11:31
At least part of this issue is due to the missing sync between the Oni2 config file and the neovim config.

Ie you can set `"editor.insertSpaces": true,` but at no point in the loading of the config is a command sent to neovim to `set expandtab`. We need to have some part of the configuration loading send those configuration options over to neovim, as well as making sure its hooked up to the configuration reloading.

Manually copying the Oni2 settings into neovim with the commandline seemed to fix/make this much better, so I think a large part of the issue is that.

**Comment by maxdietrich** [comment] 2019-05-12 15:29
You are right, I can reconstruct that this issue is solved by adding `set expandtab` to the `init.vim`. However, for the configuration option `editor.insertSpaces` to work as expected, my approach would be to add a step in the [StoreThread](https://github.com/onivim/oni2/blob/master/src/editor/Store/StoreThread.re) before `NeovimStoreConnector` is started (which loads `init.vim`) that checks if the config option is set and then ensures that init.vim contains the corresponding vim option. I'm currently a little confused though about the fact that changes to `configuration.json` seem to not find their way to the `state.configuration` object in there. Whatever changes I am making to the file, it seems like the default values that are currently set in master are always loaded 🤔What am I missing here?

**Comment by CrossR** [comment] 2019-05-12 15:36
>Whatever changes I am making to the file, it seems like the default values that are currently set in master are always loaded 🤔What am I missing here?

That will depend on the options you are looking at, but I know some aren't hooked up yet. I've hooked up the easy ones that should be over in #286, which is basically all of them except the tabs/spaces.

The spaces one should be hooked up, or at least I see it changing on my end. Are you using `Ctrl-Shift-P` to "Reload configuration" after saving? There is a separate feature of hooking up the auto reload that needs adding.

**Comment by maxdietrich** [comment] 2019-05-12 16:49
I am actually restarting oni via `esy run` to start implementing with for initial startup, since I assume that to be the easier case. I am then changing the config values in [this](https://github.com/onivim/oni2/blob/master/assets/configuration/configuration.json) file in between startups. Is that maybe the wrong way to go about it? `Cmd-Shift-P` -> `Open configuration file` closes the app for me right now.

**Comment by CrossR** [comment] 2019-05-12 18:48
When you say you are editing the `configuration.json` file, are you editing `oni2/assets/configuration/configuration.json` or `~/.config/oni2/configuration.json` (or something similar)?

That is, you might be editing the default configuration, rather than your own personal config that is loaded. That would explain why the reload does nothing, since you'd be applying changes to a different file than it expects.

The `Open configuration file` should be working....or at least it is doing for me on Windows and Linux.

**Comment by maxdietrich** [comment] 2019-05-12 19:56
Ah, I expected something like that. Unfortunately even after setting the `editor.insertSpaces` option to true in both of the files and reloading the configuration, `state.configuration.editorInsertSpaces` is still false when I log it in `editor/Store/StoreThread.re`. So to me it looks like it is not hooked up, which is weird when it seems to on your side 🤔 

Regarding the `Open configuration file`, there is no console output for me indicating why the app just closes. Is there additional logging outside of stdout which I could look into?

The fact that both of these things occur feel like Oni can't seem to properly locate my `~/.config/oni2/configuration.json` or something like that.

**Comment by bryphe** [comment] 2019-06-27 02:59
This should be fixed now with #336 - we infer the indentation when `editor.detectIndentation` is `true` (the default) - this should work for the majority of these cases (and when it can't infer - it falls back to the config). Let me know if you're still seeing issues here!

**Closed by bryphe** 2019-06-27 02:59 UTC
Labels: bug, daily editor blocker
