### ISSUE TITLE
Nested Syntax Support

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#1878] opened 2020-06-06 09:43 UTC
The HTML syntax (seems) to include other syntaxes, which would make sense. I assume we don't support that since we get this:

![image](https://user-images.githubusercontent.com/10038688/83941305-31e8a880-a7e2-11ea-8637-14657981c54e.png)

Right now, where styling drops off when we hit the style tags. Removing that section returns it to normal (except the script tag, which I'm assuming is the same issue again).

**Comment by bryphe** [comment] 2020-08-27 23:12
We actually have nested syntax support:

![image](https://user-images.githubusercontent.com/13532591/91503634-d299b200-e87f-11ea-8956-eb4a2247c0d7.png)

but it happened that this same bug impacting #1933  (fixed in #2301): https://github.com/onivim/oni2/pull/2301 happened to affect nested syntaxes also (they were more likely to hit the issue in #1933 )

The main thing we're missing, though, is [injection grammar](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) support - tracked in https://github.com/onivim/oni2/issues/2118

**Comment by bryphe** [comment] 2020-08-27 23:12
I'll close this out as a duplicate of #1933, and use #2118 to track the injection grammar work

**Closed by bryphe** 2020-08-27 23:12 UTC
Labels: A-syntax-highlighting, R-duplicate, bug
