### ISSUE TITLE
Esy install fails on OSX

### ISSUE THREAD

**Issue by m-czernek** [onivim/oni2#1775] opened 2020-05-16 07:32 UTC
Esy install exits with the following error:

```
mbp:oni2 marek$ esy install
info install 0.6.2 (using package.json)
.... fetching shelljs@0.8.4esy: internal error, uncaught exception:                                    
     Unix.Unix_error(Unix.ENOTEMPTY, "rename", "/Users/marek/onivim/oni2/_esy/default/tmp/esy-8e41d5")
     Raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
```

Thoughts on what's causing this?

**Comment by glennsl** [comment] 2020-05-16 09:04
See #1582. This is usually caused by a previous error that aborted the build, so try addressing that problem (usually `ulimit -Sn 4096`, or free up some more disk space), remove `_esy` then try again.

I'll close this as a duplicate, but feel free to continue to comment or ask any questions you have here.

**Closed by glennsl** 2020-05-16 09:04 UTC
Labels: A-technical, S-duplicate
