### ISSUE TITLE
Oni does not support HiDPI on Linux

### ISSUE THREAD

**Issue by wezm** [onivim/oni2#526] opened 2019-07-31 23:41 UTC
**OS:** Arch Linux

Oni does not automatically scale according to the display DPI.

I use a 24" 4K display. Applications typically automatically scale according to the X.org DPI:

```
xdpyinfo|grep resolution
  resolution:    192x193 dots per inch
```

or the GTK scaling, `GDK_SCALE=2` in environment or `scaling-factor` stored in `gesettings`:
```
gsettings get org.gnome.desktop.interface scaling-factor
uint32 2
```

Oni doesn't scale and ends up with tiny text and UI:

![Screenshot from 2019-08-01 09-33-41](https://user-images.githubusercontent.com/21787/62255433-84c63680-b440-11e9-9432-cc96e77cd011.png)

**Comment by CrossR** [comment] 2019-08-01 10:03
I think this is related to https://github.com/revery-ui/revery/issues/528 (Which I made about Windows, but in reality is about any form of scale factor that is applied).

**Comment by bryphe** [comment] 2019-09-09 14:00
Looks like we'd need to check this API? <https://developer.gnome.org/gdk3/stable/GdkMonitor.html#gdk-monitor-get-scale-factor>

**Comment by szbergeron** [comment] 2019-09-09 14:06
Something to note, Wayland seems to have its own method of doing fractional scaling that we should investigate. There's also an X provided api in the works for getting a fractional scaling value, I'll dig up the pr for it

**Comment by Drakulix** [comment] 2019-09-09 14:07
> Looks like we'd need to check this API? https://developer.gnome.org/gdk3/stable/GdkMonitor.html#gdk-monitor-get-scale-factor

That would work on gnome, but not necessarily on other desktop environments.

For wayland, this is given by the api, but I think that this is not supported by revery?
For X11 you may try to infer this from the DPI value of the connected monitor *or* different environment variables (GDK_SCALE for gdk, QT_AUTO_SCREEN_SCALE_FACTOR for Qt, ELM_SCALE for elementary, revery might want to introduce it's own variable to allow users to override this) *or* by compositor specific api's (e.g. the linked `GdkMonitor`), but no exclusively as there are a lot smaller project like i3,awesome,etc, that are not Gnome or KDE.

**Comment by szbergeron** [comment] 2019-09-09 14:08
There's a bunch of issues that stem from inferring scale based on suggested DPI, so I would strongly suggest waiting for the Xorg scaling api for a bit to see if it gets merged. If it does, that would be the ideal way of getting that information

**Comment by szbergeron** [comment] 2019-09-09 14:16
See WIP api @ https://gitlab.freedesktop.org/xorg/xserver/merge_requests/111

**Comment by awilkins** [comment] 2019-10-14 14:20
Trying out `d971056`

My display scaling is set to 1.75 on both monitors (same resolution, one laptop panel). Transitioning from one screen to another causes the scaling in the app window to change when the centre of the window crosses the line!

`--force-scale-factor` doesn't seem to be present as a recognized arg in this build.

**Comment by CrossR** [comment] 2019-10-14 14:39
@awilkins the flag is actually `--force-device-scale-factor`, the PR was just named before the CLI flag was confirmed. Using that flag should work hopefully!

**Comment by CrossR** [comment] 2019-10-23 22:09
Is this able to be closed with the scaling changes that have been added to respect `GDK_SCALE` and a flag to override?

**Comment by bryphe** [comment] 2020-03-21 21:28
I'll close this out for now, as we now respect the `GDK_SCALE` environment variable - but please feel free to open a new issue if there are still scaling issues here.

**Closed by bryphe** 2020-03-21 21:28 UTC
Labels: A-ux, I-daily-editor-blocker, U-revery, bug, platform-linux
