### ISSUE TITLE
Command Palette scroll during navigation

### ISSUE THREAD

**Issue by jrwrigh** [onivim/oni2#802] opened 2019-10-02 18:22 UTC
Currently the command palette doesn't scroll when you're going between options and you get past the options displayed on the view window.

Reproduce:
1) Type `:s`
2) Use `Ctrl-n` to move down the list until it moves past the last item displayed

OS: Manjaro 18.1
Oni2 Version: Just downloaded off the site and installed on the system (version command doesn't work, see #538).

**Comment by necabo** [comment] 2019-10-06 09:09
Possible duplicate of #469.

**Comment by CrossR** [comment] 2019-10-06 15:41
Yep this looks like a duplicate! Thanks for raising though, and make sure to :+1: the other issue as well.

**Closed by CrossR** 2019-10-06 15:41 UTC
Labels: bug
