### ISSUE TITLE
Closing welcome window prevents opening of any more tabs

### ISSUE THREAD

**Issue by anan44** [onivim/oni2#1470] opened 2020-03-14 08:05 UTC
If user closes the welcome window before opening any other tabs, it causes a state where no tabs are open but the editor is still open. In this state it is not possible to open any new tabs, in other words it is not possible to open any files.

**Comment by DanielPower** [comment] 2020-03-29 20:47
Can you provide more detailed steps to reproduce? For me, if I close the Welcome tab on a new window, Onivim closes. This may not be the desired behavior either, (I think it would be better for the editor to remain open with no tabs, like how VS Code, Sublime, and Atom work), but it does not match the behavior you describe.

**Comment by anan44** [comment] 2020-03-30 06:12
I actually had to think about this a bit before I managed to re-create this issue.

Try this:
1) Open onivim2 - You should only have now welcome tab open.
2) Open any file
3) Make changes to this file WITHOUT saving them.
4) Close both tabs by pressing CMD+W (on mac) twice.
5) Now you should be in a state, where you can no longer open new tabs.

**Comment by DanielPower** [comment] 2020-03-30 17:46
Ah, I can reproduce this. This seems to be related to the unsaved changes warning not appearing if you close a file using Cmd+W / Ctrl+W. Note that in this state, if you try to exit Onivim it warns you of unsaved changes.

**Comment by bryphe** [comment] 2020-05-16 19:32
Thanks for logging this issue, @anan44 ! The no-new-tabs opening in this case is fixed by #1776, so I'll close this out.

We still have to fix the fact that unsaved buffers let you close them in some cases, though (https://github.com/onivim/oni2/issues/417)

**Closed by bryphe** 2020-05-16 19:32 UTC
Labels: A-workspace, bug
