### ISSUE TITLE
Numeric prefix for commands deletes too much

### ISSUE THREAD

**Issue by fschoenm** [onivim/oni2#1066] opened 2019-12-17 10:56 UTC
Prefixing a command like ``x`` or ``s`` or ``dd``  with a number does not work correctly because sometimes the number seems to be squared (?).

For example on a simple line like ``123456789012345678901234567890`` using ``1x`` deletes 1 character, ``2x`` deletes 4 chars, ``3x`` deletes 9 chars, and so on. The same happens for example with ``2dd``, which deletes 4 lines or ``2s`` which replaces 4 characters.

Combined with movements, this seems to work. For example ``d2l`` correctly deletes 2 characters.

I don't know how to find out which version I have but it's the latest build from today running on Ubuntu or Windows.

**Comment by glennsl** [comment] 2019-12-17 11:22
Duplicate of #561, but thanks for reporting!

**Closed by glennsl** 2019-12-17 11:22 UTC
Labels: A-vim, U-libvim, bug, duplicate

**Comment by glennsl** [comment] 2019-12-17 11:24
Also make sure to give that issue an upvote to give it higher priority!

**Comment by fschoenm** [comment] 2019-12-18 08:41
> Also make sure to give that issue an upvote to give it higher priority!

Thanks. I will because this bug unfortunately makes the editor unusable for me.

**Comment by glennsl** [comment] 2019-12-18 11:07
Added `I-daily-editor-blocker` to is as well. That should also help.
