### ISSUE TITLE
Onivim2 won't launch on MacOS via the Dock

### ISSUE THREAD

**Issue by dane-harnett** [onivim/oni2#2659] opened 2020-11-02 03:50 UTC
I have installed 
Version: 0.5.1-nightly
Date: 2020-11-01T04:43:58.038Z
Commit: 28e55c7a

And when I click Onivim2 in the Dock, it bounces for a couple of minutes and eventually stops, right clicking on the icon says "Application not responding" and I have to force quit.

Since I added Onivim2 to the system path from the previous 0.5.0 version, I am able to run oni2 from the terminal and then the window opens as expected and I am able to use the program.

I am on macOS Version 10.15.7 (19H2)

**Comment by bryphe** [comment] 2020-11-03 01:08
Thanks for reporting the issue, @dane-harnett !

> Since I added Onivim2 to the system path from the previous 0.5.0 version, I am able to run oni2 from the terminal and then the window opens as expected and I am able to use the program.

Glad you have this workaround.

I suspect this is a regression from this PR: https://github.com/onivim/oni2/pull/2634 - it sounds like the shell process we are running is hanging when we try and query for the environment. I need to revisit to see a more robust approach.

I wasn't able to reproduce, though - just curious, do you have any customizations to your terminal shell?

**Comment by dane-harnett** [comment] 2020-11-03 01:12
I am using iTerm2 and oh-my-zsh

**Comment by dane-harnett** [comment] 2020-11-03 01:13
I also have an `ssh-agent add` command in my .zshrc which requires a passphrase

**Comment by dane-harnett** [comment] 2020-11-03 01:15
Ah i removed the following from my .zshrc and Onivim2 launches as expected!
```
ssh-agent | source /dev/stdin
ssh-add ~/.ssh/id_rsa
```

**Comment by bryphe** [comment] 2020-11-03 01:25
Oh, thanks @dane-harnett - that's very helpful! That explains why I couldn't reproduce :+1: 

Cool, we should certainly be more robust in that case - definitely shouldn't hang for scripts like that

**Comment by bryphe** [comment] 2020-11-06 22:14
This should be fixed now with #2670 - `stdin` is now closed when we try and spin up a terminal to inspect the environment, so shouldn't hang anymore

**Closed by bryphe** 2020-11-06 22:14 UTC
Labels: I-daily-editor-blocker, bug
