### ISSUE TITLE
Opening Changelog crashes program on macOS

### ISSUE THREAD

**Issue by zbaylin** [onivim/oni2#1758] opened 2020-05-13 17:15 UTC
Opening the Command pallete (⌘+Shift+P) and trying to open the changelog randomly crashes on macOS.

Running with `--debug` produces this:
```
[ERROR]    +2ms Oni2.Exception : Exception (Sys_error
  "/Users/zbaylin/Development/oni2/_esy/default/store/i/oni2-ecad36e8/bin/changelog.xml: No such file or directory"):
```

That file, in fact, does not exist, but running `find _esy -name "changelog.xml"` produces
```
_esy/default/store/b/oni2-ecad36e8/install/default/bin/changelog.xml
_esy/default/store/b/oni2-ecad36e8/default/assets/changelog.xml
```

This originates from here:
https://github.com/onivim/oni2/blob/f6d0d8e1568ea50e4d1608f8507340e2d4555596/src/Feature/Changelog/Feature_Changelog.re#L105-L107

I think it's a file permission bug or something with esy, but I'm not sure of that.

**Comment by glennsl** [comment] 2020-05-13 17:22
Have you checked whether or not you can reproduce it with the dmg?

**Comment by glennsl** [comment] 2020-05-13 17:24
Also, have you tried wiping `_esy`?

**Comment by zbaylin** [comment] 2020-05-13 17:25
I have wiped `_esy`. It _seems_ to work reliably with the DMG, but it sometimes (randomly as far as I can tell) works just from `esy run`

**Comment by glennsl** [comment] 2020-05-13 17:29
I have recently had major issues with other assets disappearing, but that was fixed by just not using `vscode-reasonml`, as it seems to be doing something really abusive too `esy`. But you'd definitely have noticed if it was that, as it manifests itself by crashing immediately, not rendering any text and so on.

One thing worth trying is to move it into a subdirectory of `assets`. All other assets are in subfolders, but I didn't do that for this as it seemed pointless for a single file. But perhaps there's a technical reason for it.

**Comment by zbaylin** [comment] 2020-05-13 17:32
I actually do think it has to do with `vscode-reasonml`. I had that thought, so I tried running Oni not pointed at it's own directory and it seemingly doesn't crash if I do that.

**Comment by glennsl** [comment] 2020-05-13 17:48
In that case you can avoid it by building the project before running `oni2`, as it should then pick up `ocamllsp` instead.

**Comment by bryphe** [comment] 2020-05-15 01:22
It seems like we should be more resilient in this situation, in any case - we shouldn't crash if we can't load the changelog. IMO, we should return an `Error(_)` from `Feature_Changelog.read` if it can't be loaded, and then just have some boilerplate UI like `Error loading changelog`

**Closed** 2020-05-15 15:01 UTC
Labels: A-other, I-crash, bug
