### ISSUE TITLE
libvim error thrown on empty '/' search

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#727] opened 2019-08-31 03:40 UTC
## What?
When searching with '/' deleting characters back to the initial search will throw a libvim error when the string becomes empty. Successive deletes will throw repeated errors (not pictured).

The first error is certainly a bug, but I would also say successive throws on delete are also atypical. The default behavior in neovim is to delete the search character, '/', and return the cursor to its previous location.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10119394/64058838-dadce580-cb76-11e9-8883-4f22e208149b.gif)

**Comment by instantepiphany** [comment] 2019-09-13 11:38
I'll look at this, but don't let that stop anyone else from working on it, as its my first for this project and I'm not familiar with most of the stack, and therefore it may not be finished quickly.

**Comment by instantepiphany** [comment] 2019-09-28 00:53
I'll retest this as input has changed as of https://github.com/onivim/oni2/pull/786/

**Comment by instantepiphany** [comment] 2019-10-04 13:14
Still present as of `9c092e5`.

**Comment by instantepiphany** [comment] 2020-05-01 08:50
Still present on 0.4.0 release.

I tried digging through onivim2, libvim, and the reason layer but couldn't find the problem.

**Comment by bryphe** [comment] 2020-11-25 01:42
I can no longer reproduce in latest builds, I believe this to be fixed by: https://github.com/onivim/libvim/pull/228

**Closed by bryphe** 2020-11-25 01:42 UTC
Labels: A-vim, U-libvim, bug
