### ISSUE TITLE
Paste on new line when "vim.useSystemClipboard" has "paste"

### ISSUE THREAD

**Issue by JorgeDLG** [onivim/oni2#1557] opened 2020-04-04 12:07 UTC
When "vim.useSystemClipboard" has "paste" option, when you copy/paste a string (without end of line), this is pasted on a new line. This behaviour differs with classic vim.

**Comment by pkariz** [comment] 2020-04-04 12:34
i believe that's a duplicate of #660

**Comment by glennsl** [comment] 2020-04-04 12:53
Indeed. Thanks @pkariz!

**Closed by glennsl** 2020-04-04 12:53 UTC
Labels: A-vim, bug, duplicate
