### ISSUE TITLE
Sneak mode to navigate a file

### ISSUE THREAD

**Issue by mxstbr** [onivim/oni2#2078] opened 2020-07-08 09:36 UTC
I like to use sneak mode to navigate the text in a file, however when I press <kbd>CTRL+g</kbd> in Oni only the interface shows the sneak shortcuts.

How can I enable sneak mode to navigate a file?

**Comment by kinglouie** [comment] 2020-07-09 11:56
I feel like this should be vim territory, what benefit would this feature provide over the usual vim motions?
Also how would you go about setting the actual sneak target tokens?

**Comment by mxstbr** [comment] 2020-07-09 12:23
It's how [vim-sneak](https://github.com/justinmk/vim-sneak) and [vim-easymotion](https://github.com/easymotion/vim-easymotion) work, two very popular vim plugins... Pretty standard way to navigate with vim from what I can tell 🤷

**Comment by CrossR** [comment] 2020-07-09 13:52
This sounds like a duplicate of #517, so its not something we have yet unfortunately.

It feels like something we'd need to do as a native Oni2 feature/plugin, since the vim plugins for it will probably be a pain to support, and I expect the VSCode "equivalents" won't be "vim-y" enough (that wasn't a very concrete description, but hopefully you get what I mean).

I'll stick a link to #517 some where so we can think about it in the next milestone, which we should be tackling more Vim integration stuff, since it falls into the interesting middle part where the VSCode equivalent isn't really enough, but we can't easily support the Vim version (since its got UI related elements and right now we don't get any of that info from Vim, since syntax HLs etc are all done with a separate native lib etc). If there is any other plugins that fall into that gap, it would be useful to know about.

I do use vim-sneak in my terminal nvim, so its something I'd be interested in supporting.

**Closed by CrossR** 2020-07-09 13:52 UTC
