### ISSUE TITLE
can't install tabnine extension

### ISSUE THREAD

**Issue by scottming** [onivim/oni2#2583] opened 2020-10-15 08:38 UTC
![image](https://user-images.githubusercontent.com/12830256/96098489-be2f7880-0f04-11eb-9ec3-ffbae28c1ab8.png)

**Comment by scottming** [comment] 2020-10-15 08:39
But I found the extension is downloaded.

```bash
➜  ~ ll ~/.config/oni2/extensions/TabNine.tabnine-vscode-2.8.8
total 56
-rw-r--r--   1 scottming  staff   1.0K Oct 15 16:37 LICENSE.txt
-rw-r--r--   1 scottming  staff   938B Oct 15 16:37 README.md
drwxr-xr-x   3 scottming  staff    96B Oct 15 16:29 binaries
drwxr-xr-x   6 scottming  staff   192B Oct 15 16:29 node_modules
drwxr-xr-x  26 scottming  staff   832B Oct 15 16:29 out
-rw-r--r--   1 scottming  staff   2.0K Oct 15 16:37 package.json
-rw-r--r--   1 scottming  staff    13K Oct 15 16:37 small_logo.png
```

**Comment by CrossR** [comment] 2020-10-15 12:37
Looks like a failure to parse the `package.json` as our decoder isn't set up to deal with the `type` field they are using.

```
[ERROR]    +0ms Exthost.Extension.Scanner : Failed to parse C:\Users\ryan\AppData\Local\Oni2\extensions\TabNine.tabnine-vscode-2.8.8\package.json:
        I tried the following decoders but they all failed:
  "list" decoder:
    while decoding a list:
      element 0:
        in field "properties":
          Failed while decoding key-value pairs:
            I tried the following decoders but they all failed:
              "list" decoder:
                while decoding a list:
                  element 1: Expected a string, but got null

              "single" decoder:
                Expected a string, but got [ "boolean", null, "number" ]




  "single" decoder:
    Expected an object with an attribute "properties", but got
    [
  {
    "title": "TabNine",
    "properties": {
      "tabnine.disable_line_regex": {
        "type": "array",
        "default": [],
        "description":
          "Disable TabNine when the current line contains a match of any of the provided regexes. For example, add \"require\" to disable TabNine when the current line contains the word 'require'."
      },
      "tabnine.disable_file_regex": {
        "type": "array",
        "default": [],
        "description":
          "Disable TabNine when the file path contains a match of any of the provided regexes. For example, add \"[.]js$\" to disable TabNine in JavaScript files."
      },
      "tabnine.experimentalAutoImports": {
        "type": [ "boolean", null, "number" ],
        "default": null,
        "description":
          "Experimental: Enable modules auto-import following applying TabNine suggestions"
      }
    }
  }
]
```

https://github.com/codota/tabnine-vscode/blob/master/package.json#L113-L117

So I think the first place is fixing that loading, then can see if that is the only blocker, or if there are follow up issues.

**Comment by CrossR** [comment] 2020-10-16 09:53
Fixing the install is easy enough, just needs the type parsing to be `list(nullable(string))` not `list(string)`. That gets it to install, then the next issue is that there is seemingly a missing part of the API to do with launching a web server of some kind, assumedly to power the completions.

I'm not surprised that bit is missing though. Will have to check the sort of call it is making and see. Will update when I get chance to find that error message.

**Comment by bryphe** [comment] 2020-11-07 01:04
Thanks for the investigation, @CrossR ! I pushed up a couple initial fixes here #2684

**Comment by John0x** [comment] 2021-02-23 11:39
Is this expected to work already? Cause it seems to work partially. Normally you type "TabNine::sem" to activate semantic autocomplete, but that doesn't seem to be supported yet, right?

**Comment by PedroHLC** [comment] 2021-03-03 14:22
I think this issue can be closed, it installs, and when autocompleting we have tabnine suggestions
![image](https://user-images.githubusercontent.com/1368952/109818961-54dda700-7c12-11eb-9c37-d2f15967bda0.png)
(this is in Linux, a fd265edbd build)

> Normally you type "TabNine::sem" to activate semantic autocomplete, but that doesn't seem to be supported yet, right?

![image](https://user-images.githubusercontent.com/1368952/109819372-c0277900-7c12-11eb-8cbf-5d8f60f64466.png)

**Comment by John0x** [comment] 2021-03-04 12:53
FIleType: .tsx
Oni version: 0.5.9-nightly (0.5.1935)

![image](https://user-images.githubusercontent.com/5455173/109966471-980e4780-7cf0-11eb-9fff-c1b29fdfc0fb.png)
![image](https://user-images.githubusercontent.com/5455173/109966819-fa674800-7cf0-11eb-8b49-1bcf6c8417e8.png)

Did this just not land in the nightly yet?

**Comment by bryphe** [comment] 2021-04-05 22:22
I believe the TabNine blockers should all be addressed with these PRs:

- #3318 
- #3276 
- #3274 
- #2684 

Seems to be working decent in latest nightly:

![2021-03-17 11 53 52](https://user-images.githubusercontent.com/13532591/111522908-f2a79a80-8717-11eb-8a3f-e0a250b3d4ff.gif)

I'll close this out, since it's definitely installable now - but please feel free to log a new issue if there is any unexpected behavior.

**Closed by bryphe** 2021-04-05 22:22 UTC
Labels: A-extension, bug
