### ISSUE TITLE
How do I get Onivim2 to auto format a file after saving?

### ISSUE THREAD

**Issue by aaronamm** [onivim/oni2#2814] opened 2020-12-10 08:57 UTC
Hello 
I use Onivim 2 (0.5.1-nightly), have already activated a license key, installed [EditorConfig plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) and expect the IDE will automatic format my code after I saved it.

Here is my .editorconfig:
```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 4
insert_final_newline = true

# Matches multiple files with brace expansion notation
[*.{js, ts, jsx, tsx, .yml}]
indent_size = 2
```

I also tried:
- ctrl+shift+p
- Formatting to format a document manually but it does not work.

Please let me know if I miss some configurations.

Thank you.

**Comment by dcalhoun** [comment] 2020-12-10 16:09
This may be a duplicate of #2464.

**Comment by aaronamm** [comment] 2020-12-10 18:07
> This may be a duplicate of #2464.

@dcalhoun  Thank you so much.

**Comment by bryphe** [comment] 2020-12-11 23:57
Thanks for logging the issue @aaronamm , and for catching the dup @dcalhoun !

Will track this with #2464 :+1:

**Closed by bryphe** 2020-12-11 23:57 UTC
Labels: A-formatting, R-duplicate, bug
