### ISSUE TITLE
Have to hit f twice in input fields

### ISSUE THREAD

**Issue by tristil** [onivim/oni2#2170] opened 2020-07-23 19:13 UTC
When I type 'f' in an input field, for example the search input, the first time I press f nothing happens. Hitting it again outputs f. 

![screencast 2020-07-23 15-08-20](https://user-images.githubusercontent.com/15716/88328847-0ae52800-ccf7-11ea-8cf6-ea54f4ec8a5d.gif)

**Comment by bryphe** [comment] 2020-07-24 01:23
Wow, that's a weird one - thanks for the gif, @tristil ! It's clearly getting the keyboard input...  just deciding not to add it to the text...

I just tried to reproduce and I couldn't on OSX with the latest master - so a couple of questions to help narrow it down:
- Do you have any custom configuration or a customized `keybindings.json`?
- Which platform are you on?

Having the logs might help too (via `esy run -f --trace`)

**Comment by tristil** [comment] 2020-07-24 03:18
Here are my keybindings. It's definitely responding to all of them. `g` `f` or `space`

```
[
   { "key": "<space>fs", "command": "workbench.action.files.save", "when": "normalMode" },
   { "key": "<space>wd", "command": "view.closeEditor", "when": "normalMode" },
   { "key": "<space>wk", "command": "window.moveUp", "when": "normalMode" },
   { "key": "<space>wj", "command": "window.moveDown", "when": "normalMode" },
   { "key": "<space>wh", "command": "window.moveLeft", "when": "normalMode" },
   { "key": "<space>wl", "command": "window.moveRight", "when": "normalMode" },
   { "key": "<space>wv", "command": "view.splitVertical", "when": "normalMode" },
   { "key": "<space>'", "command": "terminal.new.horizontal", "when": "normalMode" },
   { "key": "<space>pf", "command": "workbench.action.quickOpen", "when": "normalMode" },
   { "key": "<space>el", "command": "workbench.actions.view.problems", "when": "normalMode" },
   { "key": "<space>pt", "command": "explorer.toggle", "when": "normalMode" },
   { "key": "<space>/", "command": "workbench.action.findInFiles", "when": "normalMode" },
   { "key": "gt", "command": "workbench.action.nextEditor", "when": "normalMode" },
   { "key": "gT", "command": "workbench.action.previousEditor", "when": "normalMode" },
   { "key": "fed", "command": "model.actions.configuration", "when": "normalMode" }
]

```

after looking at this I realized that this is maybe intended behavior and that I need to exclude inputs, but neither of these are working for me:

```
[
   { 
     "key": "<space>pf",
     "command": "workbench.action.quickOpen",
     "when": "normalMode && editorFocus" 
   }
]
```

That doesn't work at all.

```
   { 
     "key": "<space>pf",
     "command": "workbench.action.quickOpen",
     "when": "normalMode && !textInputFocus" 
   }
```

The input still responds to the keybindings.

If editorFocus worked here I would be fine.

**Comment by bryphe** [comment] 2020-11-25 02:09
It looks like the binding that is causing the issue is actually this one:
```
   { "key": "fed", "command": "model.actions.configuration", "when": "normalMode" }
```

However - it was actually a bug that `normalMode` was `true` when in a text input. Now, we no longer treat `normalMode` as `true` when focus is in text input - so the bindings that you have should work correctly in the latest builds:

![f-key-input-fields](https://user-images.githubusercontent.com/13532591/100173667-d093bf00-2e7f-11eb-834f-0325dee3b005.gif)

The context keys were revamped in  https://github.com/onivim/oni2/pull/2427 https://github.com/onivim/oni2/pull/2433 https://github.com/onivim/oni2/pull/2438 

I'll resolve this as fixed with those PRs, but let me know if you still see any unexpected behavior (either re-opening this issue or a new issue). Thanks for all the details!

**Closed by bryphe** 2020-11-25 02:09 UTC
Labels: A-input, bug
