### ISSUE TITLE
Overlapping window decoration on mac

### ISSUE THREAD

**Issue by marvinhagemeister** [onivim/oni2#1780] opened 2020-05-18 15:14 UTC
The window controls overlap the icons in the left panel bar. Only checked with MacOS so far.

<img width="294" alt="Screenshot 2020-05-18 at 17 14 15" src="https://user-images.githubusercontent.com/1062408/82229623-03865480-992b-11ea-8b52-ba703b89c5ff.png">

Oni version: git 14656e78c61135c2c23934cc4bd60d0443e73f14

**Comment by CrossR** [comment] 2020-05-18 16:39
This is a duplicate of https://github.com/onivim/oni2/issues/1462, so I'll close this out.

Looks like there is an ongoing fix in Revery that is linked from that issue.

**Closed** 2020-05-18 16:39 UTC
Labels: S-duplicate, U-revery, bug, platform-macos

**Comment by marvinhagemeister** [comment] 2020-05-18 16:43
Good call! Somehow it didn't turn up for me in the search when I made this one.
