### ISSUE TITLE
UTF-8 characters display is not correct

### ISSUE THREAD

**Issue by cnshsliu** [onivim/oni2#1786] opened 2020-05-19 17:16 UTC
Version 0.40 on MAC OS 10.15.4

Check this to see the filename display result in left-side explorer, 
https://mlib.liuzijin.com/dgbJAAEMyHT2AAZFwphVsn/hboGTxfQaZEs7YbaZbdze5.png

Open a simple text file with Chinese characters result in incorrect character display.

**Comment by diogomqbm** [comment] 2020-05-19 20:24
when inserting `ç` or `õ` it doesn't work either

**Comment by bryphe** [comment] 2020-05-21 01:21
Thanks for logging the issue @cnshsliu ! A few related issues:
- #868 - default font doesn't support CJK glyphs 
- #1293 - no font-fallback for missing unicode glyphs

A workaround, for now, is to bring in a font file that has CJK glyphs - documented here: https://github.com/onivim/oni2/issues/1293#issuecomment-599499581 (ie, NotoSansCJK)

There's one more blocker we're working on past the font fallback - not properly accounting for multi-width glyphs, tracked by: https://github.com/onivim/oni2/issues/1475

We're working through these, hopefully we'll have a solid font fallback story shortly.

@diogomqbm - Interesting, that might be a different issue. I'm able to insert those glyphs by copy-pasting with the default font:
![image](https://user-images.githubusercontent.com/13532591/82512973-81329780-9ac6-11ea-920d-0fec930074d8.png)

Are they not rendering correctly? Or not being input correctly? Some data points that might be helpful:
- What OS are you using?
- What keyboard layout are you using?
- Are you using a custom font?

**Comment by diogomqbm** [comment] 2020-05-21 12:30
@bryphe I'm using MacOS Catalina 10.15.4, I'm using the Brazilian-Pro keyboard layout and using [Dank Mono](https://dank.sh/) as a custom font. In the specific case where the bug occurred, I was in a `.tsx` file.

**Comment by diogomqbm** [comment] 2020-05-21 12:46
![image](https://user-images.githubusercontent.com/18554242/82560466-e7133380-9b47-11ea-853a-4170bfc731e7.png)
In this case, the `information` props text should be "Novas Avaliações".

**Comment by yusiwen** [comment] 2020-05-22 13:53
@bryphe 
The editor font can be changed by 'editor.fontFamily' to a CJK font, but the problem is those fonts in other UI windows, such as Tree window and Terminal window. How to change the font in those windows?

**Comment by diogomqbm** [comment] 2020-06-22 00:55
@bryphe It works with the default font, the problem seems to be the custom font.

**Comment by bryphe** [comment] 2020-07-18 17:34
@zbaylin - I believe this should be fixed with your merge here that brings in fallback - https://github.com/onivim/oni2/pull/2113 - would you mind double-checking that we're getting font fallback in the explorer?

**Comment by zbaylin** [comment] 2020-07-18 18:04
![image](https://user-images.githubusercontent.com/4527949/87858931-81e97d80-c8ff-11ea-885c-f3226f84b14b.png)

Looks like we're good in the file explorer!

**Comment by zbaylin** [comment] 2020-07-21 18:54
I'm going to close this out since the root issue is fixed. If you have any issues with the implementation, please feel free to open a new issue!

**Closed by zbaylin** 2020-07-21 18:54 UTC
Labels: A-i18n, I-daily-editor-blocker, U-revery, bug
