### ISSUE TITLE
Scroll with minimap causes lockup

### ISSUE THREAD

**Issue by sandersac** [onivim/oni2#2919] opened 2021-01-02 00:08 UTC
Version: 0.5.9-nightly | 19eaed77
Platform: PC

Steps: 
1. Open up a file (in my case, ~800 lines long)
2. Use the mouse to scroll up or down on the minimap. It seems going a certain distance causes the issue, not the speed you scroll.

At this point the program hangs and does not recover without force-quitting it.

**Comment by bryphe** [comment] 2021-01-04 17:29
Hi @sandersac ,

Thanks for logging the issue! I'm trying to reproduce this - a few questions to help me narrow it down:

1) What version of Windows are you using?
2) What sort of file is it -  plaintext, markdown, typescript, etc? Is the file open-source, possible for me to test with the file?
3) Are you using the mousewheel, or clicking and dragging?
4) Do you have any extensions installed?
5) Do you have any custom configuration set?

**Comment by sandersac** [comment] 2021-01-04 18:39
1. Windows 1903 (OS Build 18362.1256)
2. It is a .c file, unfortunately it is proprietary so I cannot share it :(. For completeness I tested it on a smaller .py file (~300 lines long) and this issue occurs there as well.
3. Clicking and dragging. Mousewheel seems fine.
4. Yes, besides bundled extensions I have:
   a) "CMake Tools" by ms-vscode.
   b) "Arc+ theme" by phil harmoniq (manually installed, I grabbed the repo from github and unzipped it into Onivim2\extensions\theme-arc-plus)
I also tested after uninstalling CMake tools and the problem still occurs.
 
5. No custom configurations.

**Comment by bryphe** [comment] 2021-01-04 19:38
Thanks for the details @sandersac !

I wasn't able to reproduce previously - but I am able to reproduce now. Scrolling slowly via click-and-drag in either the minimap or the file explorer scrollbar. 

It doesn't seem to reproduce for me in the `0.5.1` build - checking the staging/0.5.2 build. Working to narrow it down to a particular commit.

**Comment by bryphe** [comment] 2021-01-04 19:42
Looks like this began reproducing between `0.5.1` https://github.com/onivim/oni2/commit/66f31792d6f650f044a8d22861c82f78ff142b52 and `0.5.2` https://github.com/onivim/oni2/commit/34f4663ba5e8e7afbd1b61b406c5d16bd8c8ee3f - working to narrow down

**Comment by bryphe** [comment] 2021-01-05 16:55
This should be fixed now and picked up in the latest nightly build via #2929 (root fix is in revery: https://github.com/revery-ui/revery/commit/931f3d0bca094cb233c0445e43c056047e2a1bb6)

Let me know if you still see any issues after upgrading - thanks for pinning the reproduction steps down so well!

**Closed by bryphe** 2021-01-05 16:55 UTC
Labels: I-crash, I-daily-editor-blocker, bug

**Comment by sandersac** [comment] 2021-01-05 17:12
My pleasure! Thank you for fixing up this issue right away. I am looking forward to seeing where this project goes and making Onivim2 a more core part of my workflow as development continues :). Cheers!
