### ISSUE TITLE
Closing the last tab should not exit oni2

### ISSUE THREAD

**Issue by Ayrx** [onivim/oni2#3802] opened 2021-08-08 03:20 UTC
The current behaviour (Version 0.5.9-nightly (0.5.2196)) of oni2 on macOS is that the program exits when the last editor tab is closed.

It would be better if oni2 remains open so that you can still open new files etc and only exits when explicitly told to do so.

**Comment by jerabaul29** [comment] 2021-08-08 08:22
I actually enjoy being able to close oni2 with a simple command such as ```:qa``` that works because of this rule :) . If there is a desire for amending it in the direction you name that would be fine as long as there is a new command to simply close oni2; ```:qo``` for quit Oni for example?

**Comment by Ayrx** [comment] 2021-08-08 08:25
Maybe this could be a configurable behaviour?

**Comment by kinglouie** [comment] 2021-08-08 19:00
duplicate of #759, #1603, #3553 and #2533

**Closed** 2021-08-09 01:31 UTC
